### ISSUE TITLE
space character :S

### ISSUE THREAD

**Issue by ctecPHP** [billhsu/jUART#11]
Hello friend, forgive my English. I wonder how to send a space character. Whenever you send me the plugin returns error.

**Comment by pmrivas** [comment]
Hello:
  I had the same issue, replaced function sendtest() like this:
io.post(boost::bind(&SerialAPI::do_send, this, ' ')); //<--- Space instead of "a"..

compiled, and in javascript did:

(texto[i]==" ") ? ser.sendtest() : ser.send(texto[i]);

And now it works, btw: Linux x64
