### ISSUE TITLE
Can´t run plugin on Windows

### ISSUE THREAD

**Issue by fernandobarron** [billhsu/jUART#15]
I can´t make the plugin is available on firefox, I follow your instructios "Take FireFox for example: Copy /bin/Windows/npjUART.dll to C:\Program Files (x86)\Mozilla Firefox\plugins" and it doesnt work´.

Even I install the plugin using Windows registry with no succes:

HKLM/Software/MozillaPlugins/plugin-identifier
    Descripton: REG_SZ "Description of the Plugin"
    Path: REG_SZ "C:\..Path to the plugin.dll"
    ProductName: REG_SZ "The Plugin Name"
    Vendor: REG_SZ "The Plugin Author/Vendor"
    Version: REG_SZ "0.5.whatever plugin version string"
HKLM/Software/MozillaPlugins/plugin-identifier/MimeTypes
    Add a sub-key for each MIME type the plugin supports, with no values

I use Windows x64 and Firefox 35.0. Hope yo can help!

**Comment by billhsu** [comment]
Can you try compiling the dll on your machine first?
Or you may try restarting Firefox with admin access.

Fernando Barrón Bucio <notifications@github.com>于2015年1月20日星期二写道：

**Comment by fernandobarron** [comment]
Thanks for your reply. I recompilled the project and now it works!. I have another question, is there a method to close connections?

Thanks in advance

**Comment by billhsu** [comment]
Yep.
You can use close().

**Comment by firzen** [comment]
@fernandobarron can you send me your compilled dll ? thanks 
firzen.pan#gmail.com

**Comment by yejiabin** [comment]
@fernandobarron can you send me your compilled dll ? thank you very much!
249117523@qq.com

**Comment by fernandobarron** [comment]
@yejiabin Sure, you cand download from here https://www.dropbox.com/s/ah7zvhjfjl7qcni/npjUART.dll?dl=0. Hope it helps you

**Comment by yejiabin** [comment]
thank for your file!But it still do not work in my project.
plugin().Serial is still 'undefined',i do not know why.This is my screen-capture:
![image](https://cloud.githubusercontent.com/assets/22442360/18858443/b481e45c-849e-11e6-9b90-b5b7337187ca.png)

**Comment by fernandobarron** [comment]
You need to check if the plugin is listed on firefox plugins
![sin titulo](https://cloud.githubusercontent.com/assets/8146121/18858562/7d4e822c-8432-11e6-86a7-fa65d550627a.png)

**Comment by yejiabin** [comment]
I have coped 'npjUART.dll' to 'C:\Program Files (x86)\Mozilla Firefox\plugins'.
But i can not find it in firefox plugin:
![image](https://cloud.githubusercontent.com/assets/22442360/18859446/addc4cf2-84a6-11e6-8888-ce7a53a68fa4.png)

Did I need to take any other steps?

**Comment by fernandobarron** [comment]
Try to copy dll to C:\Users\'Your User'\AppData\Roaming\Mozilla\Firefox\plugins

**Comment by yejiabin** [comment]
I'm sorry,my directories do not have the Folder of plugins:
![image](https://cloud.githubusercontent.com/assets/22442360/18860307/a22b80c8-84ae-11e6-84d1-3f0e31b354c5.png)

**Comment by fernandobarron** [comment]
Try to create plugins directory on C:\Users\'Your User'\AppData\Roaming\Mozilla\Firefox\

If that doesn't work maybe you need to recompile the project.

**Comment by yejiabin** [comment]
Thanks for your reply.
the problem lies in the version of firefox.

**Comment by X-Y** [comment]
It's not working with Firefox 52 as I've tested.

**Comment by billhsu** [comment]
Can you try recompiling the library on your machine?

**Comment by fernandobarron** [comment]
Firefox 52 no longer supports plugins :(

**Comment by billhsu** [comment]
Oh.. That's so sad..

**Comment by blindshell** [comment]
You can try re-enabling plugins by adding plugin.load_flash_only = true in about:config. As for FF v 54, it still works...
