### ISSUE TITLE
Data Received is truncated

### ISSUE THREAD

**Issue by fernandobarron** [billhsu/jUART#16]
When sending a string of more than 512 characters the recv function only gets the first 512 characters and then stops receiving, is there any way to increase reading ability?

**Comment by billhsu** [comment]
Will look into it.

**Comment by fernandobarron** [comment]
I resolved my problem!
Found a constant in SerialAPI.h file
 static const int max_buffer_length = 512;
and change the value to 2048, then I recompiled the project and now i can read more than 512 characters.
