### ISSUE TITLE
Invalid Plugin ?

### ISSUE THREAD

**Issue by Blumax** [billhsu/jUART#19]
I have add npjUART.so to /usr/lib/mozilla/plugins/

The file : /home/USER/.mozilla/firefox/5b6bl9nk.default/pluginreg.dat

Generated File. Do not edit.

[HEADER]
Version:0.17:$
Arch:x86-gcc3:$

[PLUGINS]

[INVALID]
/usr/lib/mozilla/plugins/npjUART.so:$
1432420681000:$

I don't find solution :(

I'm use Debian i386 witch Iceweasel, but it same witch Firefox.

**Comment by billhsu** [comment]
You may need to recompile the plugin on your machine.

**Comment by Blumax** [comment]
It's OK ! Tank you :)
Thank you for this great project !
I'm going to do a project very quickly thanks to that!
