### ISSUE TITLE
Serial.open() behaves unexpectedly if re-opened when already open

### ISSUE THREAD

**Issue by gmkarl** [billhsu/jUART#28]
If serial is already open, Serial.open(newdevice) will presently
1. report an error when asio throws
2. replace the "device" member of its c++ class with newdevice (this member is unused)
3. stay connected to the old device
4. return true

I propose it either
1. return false if already open, and not replace "device"
or
2. close the old device automatically if open() is called when already open

**Comment by billhsu** [comment]
@gmkarl let's go with proposal 2
