### ISSUE TITLE
JsError: plugin().Serial is not defined

### ISSUE THREAD

**Issue by yejiabin** [billhsu/jUART#46]
My environment is  WIN7 64bit.
My browser is Firefox.
I have coped the /bin/Windows/npjUART.dll into my browser's plugin directory.
But i can't get plugin().Serial Object,
Did I need to take any other steps?
Thank you for answer!

**Comment by billhsu** [comment]
@yejiabin can you try recompiling the dll on your machine?

**Comment by yejiabin** [comment]
I have solved this problem,thanks!
